services:
  telegram-bot:
    build: .
    restart: unless-stopped
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - ALLOWED_USERS=${ALLOWED_USERS}
    volumes:
      - ${SAVED_FILES_PATH}:/app/saved_files
    healthcheck:
      test: ["CMD", "python", "-c", "import os; print('Bot is running')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
