services:
  telegram-bot:
    build: .
    restart: unless-stopped
    user: "1000:1000"  # Run as host user to avoid permission issues
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - ALLOWED_USERS=${ALLOWED_USERS}
      - ROOT_DOWNLOAD_PATH=/app/downloads
      # Performance optimizations
      - CHUNK_SIZE=8192
      - MAX_CONCURRENT_DOWNLOADS=3
      - DOWNLOAD_TIMEOUT=300
      - NOTIFICATION_COOLDOWN=2.0
      - MAX_FILE_SIZE=1073741824
      - MIN_FREE_SPACE=1073741824
      - ASYNC_IO_TIMEOUT=30.0
      - MAX_RETRIES=3
      - LOG_LEVEL=INFO
      - ENABLE_DEBUG_LOGGING=false
    volumes:
      - ${SAVED_FILES_PATH}:/app/downloads
    deploy:
      resources:
        limits:
          cpus: '1.0'  # Limit to 1 CPU core
          memory: 512M  # Limit to 512MB RAM
        reservations:
          cpus: '0.25'  # Reserve 0.25 CPU core
          memory: 128M  # Reserve 128MB RAM
    healthcheck:
      test: ["CMD", "python", "-c", "import os; print('Bot is running')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
