name: 🚀 Pipeline Script CI/CD

on:
  push:
    branches: [ main, develop, feature/*, bugfix/*, hotfix/* ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      API_ID: 1234
      API_HASH: dummy
      BOT_TOKEN: dummy
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Make pipeline script executable
      run: |
        chmod +x scripts/pipeline.sh
        
    - name: Run full pipeline
      run: |
        echo "🚀 Running full pipeline..."
        ./scripts/pipeline.sh
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false 